language: python

matrix:
  include:
    - python: "3.6"

install:
  - if [ -z "$TRAVIS_TAG" ]; then exit 0;  fi
  - pip install awscli

script:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.29/hugo_0.29_Linux-64bit.tar.gz -O hugo.tar.gz
  - tar xvzf hugo.tar.gz
  - rm -rf "./public/"
  - ./hugo
  - aws s3 sync --acl public-read --sse --delete "./public/" s3://www.joc-gafo.org
  - coverage run --source=blockschaltbilder setup.py test
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id EPNLPWEUBLA8I --paths '/*'
